services:
  node:
    build: .
    platform: linux/arm64
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
